[package]
org = "ballerinax"
name = "azure.functions"
version = "@toml.version@"
distribution = "2201.7.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.functions"
license = ["Apache-2.0"]
keywords = ["azure", "functions", "serverless", "cloud"]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/azure.functions-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "@stdlib.mimenative.version@"
path = "./lib/mime-native-@stdlib.mimenative.version@.jar"
