[package]
org = "ballerinax"
name = "azure.functions.tests"
version = "@toml.version@"

[platform.java17]
graalvmCompatible = true

[build-options]
observabilityIncluded = true
cloud = "azure_functions"
