[package]
org = "ballerinax"
name = "azure.functions"
version = "4.2.1"
distribution = "2201.14.0-20260527-050400-74f7e6bf"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.functions"
license = ["Apache-2.0"]
keywords = ["Vendor/Microsoft", "Area/Cloud & Infrastructure", "Type/Connector", "Type/Trigger", "serverless"]

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
path = "../native/build/libs/azure.functions-native-4.2.1-SNAPSHOT.jar"

[[platform.java25.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.11.0"
path = "./lib/mime-native-2.11.0.jar"
